#!/bin/bash
#
###############################################################################
#                                                                             #
#                           WPSD Update Program                               #
#                                 by W0CHP                                    #
#                                                                             #
###############################################################################
#

if [ "$(id -u)" != "0" ]; then
  echo -e "You need to be root to run this command...\n"
  exit 1
fi

exec 200>/var/lock/wpsd-update.lock || exit 1
if ! flock -n 200 ; then
  echo -e "Another instance is already running...\n"
  exit 1
fi

script_name=$(basename "$0")

source /usr/local/sbin/.wpsd-common-funcs

export GIT_HTTP_CONNECT_TIMEOUT="10"
export GIT_HTTP_USER_AGENT="WPSD-Update (Manual-Update)"

git_checkUpdateRequired() {
    # Set the function variables
    gitFolder=${1}
    gitRemoteURL=$(git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git config --get remote.origin.url)
    # WPSD has more than one branch. So depending on what WPSD Web Code branch the user has installed, check that branch.
    gitBranch="$( git --git-dir=${gitFolder}/.git symbolic-ref --short HEAD )"

    # Git check / update function
    gitStatusRemote=$(git ls-remote --heads ${gitRemoteURL} | grep ${gitBranch} | awk {'print $1'})
    gitStatusLocal=$(git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git log ${gitBranch} --pretty=tformat:"%H" -1)

    # Return the output
    if [[ ${gitStatusRemote} != ${gitStatusLocal} ]]; then
	echo "1"
    else
	echo "0"
    fi
}

git_update() {
    local gitFolder=${1}
    local dash_branch
    dash_branch="$( git --git-dir=${gitFolder}/.git symbolic-ref --short HEAD )"
    local remote_name="origin"

    if [[ $(git_checkUpdateRequired "${gitFolder}") -gt 0 ]]; then
        echo -e "  ${COL_LIGHT_MAGENTA}${NOTE} Updates found - Installing now..."

        local current_dir=$(pwd)
        cd "${gitFolder}" || { echo "ERROR: Could not cd to ${gitFolder}"; return 1; }
        trap "cd '${current_dir}'" RETURN

        local target_branch="master"
        if [[ ${gitFolder} == "/var/www/dashboard" ]]; then
            target_branch="${dash_branch}"
        fi

        git stash clear > /dev/null 2>&1

        if [[ ${gitFolder} == "/usr/local/sbin" ]]; then
            git fetch -q "${remote_name}" master > /dev/null 2>&1
            if [ "$(git diff --name-only ${remote_name}/master 2>/dev/null | grep -x wpsd-update 2>/dev/null)" = "wpsd-update" ]; then
                echo -e "\n  ${COL_LIGHT_BLUE}${INFO} New version of the Updater available. Performing self-update..."
                git reset --hard -q "${remote_name}/master" > /dev/null 2>&1
                echo -e "  ${TICK} Updates installed!"
                echo -e "\n  ${COL_LIGHT_BLUE}${INFO} Relaunching Updater with the new version in 3 seconds..."
                sleep 4
                exec "$0" "$@"
                exit 1
            fi
            target_branch="master"
        elif [[ ${gitFolder} == "/usr/local/bin" ]]; then
            /usr/local/sbin/wpsd-services fullstop > /dev/null 2>&1
            process_log_file > /dev/null 2>&1
            target_branch="master"
        elif [[ ${gitFolder} == "/opt/cast" ]]; then
             target_branch="master"
        fi

        #echo -e "  ${COL_LIGHT_MAGENTA}${NOTE} Fetching branch '${target_branch}'..."
        git fetch -q "${remote_name}" "${target_branch}" > /dev/null 2>&1
        #echo -e "  ${COL_LIGHT_MAGENTA}${NOTE} Resetting to '${remote_name}/${target_branch}'..."
        git reset --hard -q "${remote_name}/${target_branch}" > /dev/null 2>&1

        git stash clear > /dev/null 2>&1

        if [[ $(git_checkUpdateRequired "${gitFolder}") -gt 0 ]]; then
            echo -e "  ${CROSS} Update re-sync required: forcing re-sync and update...."
	    cd /tmp
            curl -Ls -A "WPSD-Reset (Manual Update)" https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Scripts/raw/branch/master/reset-wpsd | bash > /dev/null 2>&1
	    echo -e "\n  ${COL_LIGHT_BLUE}${INFO} Sync & Reset complete: Relaunching Updater in 3 seconds..."
	    sleep 4
	    exec "$0" "$@"
        fi

        if [[ ${gitFolder} == "/usr/local/bin" ]]; then
            /usr/local/sbin/wpsd-services start > /dev/null 2>&1
        fi

        echo -e "  ${TICK} Updates installed!"
    else
        echo -e "  ${INFO} No updates required."
    fi
}

term_banner() {
    clear
    echo -e -n "${COL_LIGHT_CYAN}${BOLD}"
    echo '    _      _____  _______ 
   | | /| / / _ \/ __/ _ \
   | |/ |/ / ___/\ \/ // /
   |__/|__/_/  /___/____/'
    echo -e -n "${COL_NC}${COL_LIGHT_ORANGE}${BOLD}WPSD Software Update Utility${COL_NC}\n"
}

perform_update() {
    if [ -t 1 ]; then
    # This is running from a terminal, so it should be safe to update the OS
	if [[ "$1" == "os" || "$1" == "all" ]]; then
	    echo -e "\n${BULL} Checking for any available operating system updates."
	    echo -e "  Please wait...\n"
	    apt-get -q=2 update
	    if ! apt-get upgrade --dry-run | grep -qw "0 upgraded"; then
		echo -e "  ${COL_LIGHT_MAGENTA}${INFO} Operating system updates available; installing now..."
		apt-get upgrade --fix-missing --fix-broken -y
		apt-get -q=2 autoremove -y
		apt-get -q=2 clean
		apt-get -q=2 autoclean
		echo -e "\n"
		echo -e "  ${TICK} Operating System Updates Complete!!\n"
	    else
		echo -e "  ${INFO} No operating system updates required.\n"
	    fi
	    if [ "$1" == "os" ]; then 
	    echo -e "${BULL} ${COL_LIGHT_BLUE}${INFO} WPSD is ${BOLD}not${COL_NC} updated by using ${COL_LIGHT_BLUE}${BOLD}sudo wpsd-update os${COL_NC}"
	    echo -e "      To check for and install WPSD updates, run this"
	    echo -e "      program again as: '${COL_LIGHT_BLUE}${BOLD}sudo wpsd-update${COL_NC}'"
	    echo -e "      To check for and install WPSD and OS updates, run this"
	    echo -e "      program again as: '${COL_LIGHT_BLUE}${BOLD}sudo wpsd-update all${COL_NC}'\n"
           exit 0
        fi
	fi
    fi

    pkill .wpsd-slipstream-tasks > /dev/null 2>&1
    pkill .wpsd-running-tasks > /dev/null 2>&1

    if [ "$DISPLAY_VALUE" == "Nextion" ] ; then
	if [ "${OS_VER}" -ge "12" ] ; then
	    systemctl stop nextiondriver.service > /dev/null 2>&1
 	    /usr/local/sbin/.wpsd-nextion-text.py t1 "Please Wait..." > /dev/null 2>&1
	    /usr/local/sbin/.wpsd-nextion-text.py t0 "Updating..." > /dev/null 2>&1
	fi
    fi
    if [ "$DISPLAY_VALUE" == "OLED" ] ; then
	if [ "${OS_VER}" -ge "12" ] ; then
	    systemctl stop mmdvmhost.timer > /dev/null 2>&1
	    systemctl stop mmdvmhost.service > /dev/null 2>&1
	    /usr/local/sbin/.wpsd-oled.text.py --text1 "Updating..." --text2 "Please Wait..." > /dev/null 2>&1
	fi
    fi

    systemctl is-active --quiet cron.service && systemctl stop cron.service > /dev/null 2>&1
    systemctl is-active --quiet wpsd-running-tasks.timer && systemctl stop wpsd-running-tasks.timer > /dev/null 2>&1
    systemctl is-active --quiet wpsd-running-tasks.service && systemctl stop wpsd-running-tasks.service > /dev/null 2>&1
    systemctl is-active --quiet wpsd-nightly-tasks.timer && systemctl stop wpsd-nightly-tasks.timer > /dev/null 2>&1
    systemctl is-active --quiet wpsd-nightly-tasks.service && systemctl stop wpsd-nightly-tasks.service > /dev/null 2>&1
    systemctl is-active --quiet wpsd-cache.timer && systemctl stop wpsd-cache.timer > /dev/null 2>&1

    if [ -t 1 ] ; then
	if ! [ $(cat /lib/systemd/system/nginx.service | grep -o "mkdir") ]; then
	    sed -i '\/PIDFile=\/run\/nginx.pid/a ExecStartPre=\/bin\/mkdir -p \/var\/log\/nginx' /lib/systemd/system/nginx.service
	    systemctl daemon-reload
	    systemctl restart nginx.service
	    #echo -e "  ${NOTE} ${COL_LIGHT_YELLOW}Note:${COL_NC} Web server configuration has been updated by operating system; restarting update..."
	    exec "$0" "$@"
	    exit 1
	fi
    fi

    echo -e "\n${BULL} Checking connectivity to the WPSD Update System..."
    conn_check
    if $connection_established; then
	echo -e "  ${COL_BRIGHT_GREEN}${TICK} Connection established!\n"
    else
	echo -e "  ${CROSS} ${COL_BRIGHT_RED}ERROR:${COL_NC} Cannot connect to the WPSD Update System. Try again later. Exiting...\n"
	exit 1
    fi

    echo -e "${BULL} Updating WPSD Utilities and Support Programs..."
    git_update /usr/local/sbin
    echo ""

    echo -e "${BULL} Updating WPSD Web Dashboard Software..."
    git_update /var/www/dashboard
    echo ""

    echo -e "${BULL} Updating Hostfiles, ID & Talkgroup Databases..."
    FORCE=1 /usr/local/sbin/wpsd-hostfile-update > /dev/null 2>&1
    echo -e "  ${TICK} Done!"
    echo ""

    echo -e "${BULL} Updating WPSD Digital Voice-Related Binaries..."
    git_update /usr/local/bin
    echo ""

    # dvmega cast-specific stuff
    castResult=$(isDVmegaCast)
    if [ "$castResult" == "true" ]; then
	echo -e "${BULL} Updating WPSD DVMega CAST Software..."
	# setup local cast repo and link repo to cast PATH
	if [ ! -d '/opt/cast' ] ; then
	   cd /usr/local/sbin
	   git reset --hard > /dev/null 2>&1

	   systemctl stop castudp.service > /dev/null 2>&1
	   systemctl stop castserial.service > /dev/null 2>&1

	   git clone https://wpsd-swd.w0chp.net/WPSD-SWD/DVMega-Cast.git /opt/cast > /dev/null 2>&1
	   cd /opt/cast
	   git checkout master > /dev/null 2>&1
	   git reset --hard origin/master > /dev/null 2>&1

	   rm -rf /usr/local/cast/sbin
	   ln -s /opt/cast/usr-local-cast-sbin /usr/local/cast/sbin > /dev/null 2>&1

	   rm -rf /usr/local/cast/bin
	   ln -s /opt/cast/usr-local-cast-bin /usr/local/cast/bin > /dev/null 2>&1

	   systemctl start castudp.service > /dev/null 2>&1
	   systemctl start castserial.service > /dev/null 2>&1

	   mkdir /usr/local/cast/etc > /dev/null 2>&1
	   cp -a /opt/cast/cast-factory-settings/* /usr/local/cast/etc/ > /dev/null 2>&1
	fi
	if [ -d '/opt/cast' ] ; then
	    # setup the memory-list and firmware upgrade www symlinks if they don't exist yet.
	    if [ ! -L '/var/www/dashboard/admin/cast' ] && [ ! -d '/var/www/dashboard/admin/cast' ]; then
		ln -s /opt/cast/usr-local-cast-www /var/www/dashboard/admin/cast > /dev/null 2>&1
	    fi
	    # setup central fw upload dir.
	    if [ ! -d '/opt/cast/usr-local-cast-www/cast-firmware/fw' ]; then
		mkdir /opt/cast/usr-local-cast-www/cast-firmware/fw
	    fi
	fi
	# ensure configs always have proper perms
	chmod 775 /usr/local/cast/etc
	chown -R www-data:pi-star /usr/local/cast/etc
	chmod 664 /usr/local/cast/etc/*

	# www is a symlink so get main perms setup
	chmod 775 /opt/cast/usr-local-cast-www
	chmod 775 /opt/cast/usr-local-cast-www/cast-firmware/fw
	chown -R www-data:www-data /opt/cast/usr-local-cast-www

	git_update /opt/cast
	echo ""
    fi

    #echo -e "  ${TICK} Done!\n" # updates. complete
    
    echo -e "${BULL} Performing maintenance tasks..."

    # check if user already has firewall disabled, and if so, ensure it's kept that way.
    if [ "$fwState" == "enabled" ]; then
        /usr/local/sbin/wpsd-system-manager -efw > /dev/null 2>&1
    else
        /usr/local/sbin/wpsd-system-manager -dfw > /dev/null 2>&1
    fi

    /usr/local/sbin/.wpsd-backend-maint > /dev/null 2>&1

    # if css does not exist, install default one
    if [ ! -f "/etc/wpsd-css.ini" ] ; then
	curl -Ls -A "${uaStrSF}" $SUPPORTING_FILES_REPO/WPSD-CSS.ini -o /etc/wpsd-css.ini
    fi

    conn_check

    # log file perms
    chown -R mmdvm:mmdvm /var/log/pi-star > /dev/null 2>&1
    chmod 775 /var/log/pi-star > /dev/null 2>&1

    systemctl restart wpsd-running-tasks.service >/dev/null 2>&1

    /usr/local/sbin/.wpsd-sys-cache >/dev/null 2>&1

    systemctl is-active --quiet cron.service || systemctl start cron.service > /dev/null 2>&1
    systemctl is-active --quiet wpsd-running-tasks.timer || systemctl start wpsd-running-tasks.timer > /dev/null 2>&1
    systemctl is-active --quiet wpsd-nightly-tasks.timer || systemctl start wpsd-nightly-tasks.timer > /dev/null 2>&1
    systemctl is-active --quiet wpsd-cache.timer || systemctl start wpsd-cache.timer > /dev/null 2>&1

    if [ "$DISPLAY_VALUE" == "Nextion" ] ; then
	if ! systemctl is-active --quiet nextiondriver.service; then
	    systemctl start nextiondriver.service > /dev/null 2>&1
 	fi
    fi
    if ! systemctl is-active --quiet mmdvmhost.service; then
	systemctl start mmdvmhost.service > /dev/null 2>&1
    fi
    if ! systemctl is-active --quiet mmdvmhost.timer; then
	systemctl start mmdvmhost.timer > /dev/null 2>&1
    fi

    echo -e "  ${TICK} Done!\n" # maint. complete

    if [ -t 1 ]; then
    # This is running from a terminal, so it should be safe to update the OS
	if [[ "$1" != "os" && "$1" != "all" ]]; then
	    echo -e "${BULL} ${COL_LIGHT_BLUE}${INFO} Operating system is ${BOLD}not${COL_NC} updated by default..."
	    echo -e "      To check for and install OS updates, run this"
	    echo -e "      program again as: '${COL_LIGHT_BLUE}${BOLD}sudo wpsd-update os${COL_NC}'"
	    echo -e "      To check for and install WPSD and OS updates, run this"
	    echo -e "      program again as: '${COL_LIGHT_BLUE}${BOLD}sudo wpsd-update all${COL_NC}'\n"
	fi
    fi

    /bin/sync
    /bin/sync
    /bin/sync

    if [ -t 1 ]; then # term. vs. web output...
	echo -e "${COL_REG_CYAN}+-------------------------------------------+${COL_NC}"
	echo -e "${COL_REG_CYAN}|                                           |${COL_NC}"
	echo -e "${COL_REG_CYAN}|  ${TICK} ${COMPL} Update Process Finished!   ${COL_REG_CYAN}|${COL_NC}"
	echo -e "${COL_REG_CYAN}|                                           |${COL_NC}"
	echo -e "${COL_REG_CYAN}+-------------------------------------------+${COL_NC}\n"
    else
	echo -e "${TICK} ${COMPL} Update Process Finished!"
	echo -e "<h3><a style='color:white;text-decoration:underline;'' href='/'>Back to Dashboard <span style='font-size: 30px;'>&larr;</span></a></h3>"
    fi
}

# Do the deeds, y0!
OptIntoDiags_value=${OptIntoDiags_value:-true}
if [ -t 1 ]; then
    # run via terminal, only output to screen
    export FORCE_COLOR=1
    if [ "$OptIntoDiags_value" != 'true' ] ; then
	echo -e "\nExiting...\n"
	echo "You have opted out of updates and diagnostics."
	echo -e "To enable updates, you must opt-in via the Configuration Page.\n"
	exit 1
    else
	term_banner
	perform_update "$@"
    fi
else
    # if not run via terminal, log everything into a log file
    if [ "$OptIntoDiags_value" != 'true' ] ; then
	echo -e "\nExiting...\n" | tee -a /var/log/pi-star/WPSD-update.log
	echo "You have opted out of updates and diagnostics." | tee -a /var/log/pi-star/WPSD-update.log
	echo -e "To enable updates, you must opt-in via the <a style='color:white;text-decoration:underline;'' href='/admin/configure.php#diagsOptForm'>Configuration Page</a>.\n" | tee -a /var/log/pi-star/WPSD-update.log
	exit 1
    else
	perform_update >> /var/log/pi-star/WPSD-update.log 2>&1
    fi
fi

exit 0

